spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
zuul:
  #ignoredServices: microservice-consumer-movie-feign #'*'
  routes:
    indexname:
      path: /zuulusers/**
      serviceId: microservice-provider-user

#ribbon:
#  eureka:
#    enabled: false
#microservice-provider-user:
#  ribbon:
#    listOfServers: example.com,google.com
