server:
  port: 7901
user:
  userServicePath: http://localhost:7900/simple/
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}