server:
  port: 8060
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  application:
    name: microservice-zipkin-server

    
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: 192.168.99.100:9200
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.sleuth.zipkin: debug