server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/y_bo/spring-cloud-config-server
          repos:
            spring-cloud-config-eureka: 
              uri: https://gitee.com/y_bo/spring-cloud-config-eureka
              username: y_bo
              password: 
              
encrypt:
  key: fsadfvv3