server:
  port: 8060
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  application:
    name: microservice-zipkin-server
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/microservice?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root321
    #driver-class-name: com.mysql.jdbc.Drive
    
zipkin:
  storage:
    type: mysql
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/