spring:
  application:
    name: microservice-gateway-zuul-zipkin
  zipkin:
    base-url: http://localhost:8060
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
zuul:
  #ignoredServices: microservice-consumer-movie-feign #'*'
  routes:
    providerUser:
      path: /zuulusers/**
      serviceId: microservice-provider-user
    consumerMovie:
      path: /zuulmovie/**
      serviceId: MICROSERVICE-CONSUMER-MOVIE-FEIGN-HYSTRIX


#ribbon:
#  eureka:
#    enabled: false
#microservice-provider-user:
#  ribbon:
#    listOfServers: example.com,google.com
